/** Locked electoral-cycle file. Do not invent or paraphrase these strings. */
export const FOOTPRINT = [
  {
    id: "Madhya Pradesh",
    short: "MP",
    pcs: ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Guna", "Vidisha"],
    acs: ["Bhopal Dakshin-Paschim", "Bhopal Madhya", "Govindpura", "Indore-1", "Lashkar", "Katangi"],
    pcCount: 6,
    acCount: 30,
    cycles: "2018, 2023 Assembly | 2019, 2024 Lok Sabha",
  },
  {
    id: "Delhi",
    short: "DL",
    pcs: ["New Delhi", "Chandni Chowk", "West Delhi"],
    acs: ["Adarsh Nagar", "New Delhi", "Karol Bagh", "Rajinder Nagar"],
    pcCount: 3,
    acCount: 19,
    cycles: "2019 Lok Sabha, 2025 Assembly",
  },
  {
    id: "Maharashtra",
    short: "MH",
    pcs: ["Mumbai North", "Mumbai North-West", "Pune", "Nagpur", "Nashik"],
    acs: ["Borivali", "Kandivali East", "Shivajinagar"],
    pcCount: 5,
    acCount: 33,
    cycles: "2019 Lok Sabha",
  },
  {
    id: "Rajasthan",
    short: "RJ",
    pcs: ["Jaipur", "Jaipur Rural", "Kota"],
    acs: ["Civil Lines", "Kishanpole", "Hawa Mahal"],
    pcCount: 3,
    acCount: 22,
    cycles: "2018 Assembly, 2019 Lok Sabha",
  },
  {
    id: "Haryana",
    short: "HR",
    pcs: ["Karnal", "Sonipat", "Ambala"],
    acs: ["Karnal", "Panipat City", "Panipat Rural"],
    pcCount: 3,
    acCount: 16,
    cycles: "2019, 2024, 2025 Assembly | 2024 Lok Sabha",
  },
  {
    id: "Assam",
    short: "AS",
    pcs: ["Guwahati", "Jorhat"],
    acs: ["Jalukbari", "Dispur", "Jorhat"],
    pcCount: 2,
    acCount: 16,
    cycles: "2019 Lok Sabha",
  },
  {
    id: "Odisha",
    short: "OD",
    pcs: ["Bhubaneswar", "Cuttack", "Berhampur"],
    acs: ["Bhubaneswar North", "Barabati-Cuttack", "Nabarangpur", "Bhawanipatna"],
    pcCount: 3,
    acCount: 20,
    cycles: "2019, 2024 Lok Sabha & Assembly",
  },
  {
    id: "Telangana",
    short: "TS",
    pcs: ["Hyderabad", "Secunderabad", "Chevella"],
    acs: ["Khairatabad", "Jubilee Hills", "Amberpet", "Secunderabad"],
    pcCount: 3,
    acCount: 16,
    cycles: "2019 Lok Sabha",
  },
  {
    id: "Goa",
    short: "GA",
    pcs: ["North Goa"],
    acs: ["Panaji", "Taleigao", "Mapusa", "Calangute", "Ponda", "Margao"],
    pcCount: 1,
    acCount: 6,
    cycles: "2019 Lok Sabha",
  },
  {
    id: "Puducherry",
    short: "PY",
    pcs: ["Puducherry"],
    acs: ["Oupalam", "Orleampeth", "Kamaraj Nagar", "Lawspet", "Kalapet", "Thattanchavady", "Raj Bhavan"],
    pcCount: 1,
    acCount: 7,
    cycles: "2019 Lok Sabha",
  },
  {
    id: "Jammu and Kashmir",
    short: "JK",
    pcs: ["Srinagar", "Jammu", "Baramulla", "Anantnag-Rajouri", "Udhampur"],
    acs: ["Srinagar", "Jammu East", "Jammu West", "Anantnag", "Baramulla", "Udhampur"],
    pcCount: 5,
    acCount: 15,
    cycles: "2025 Assembly (25 targeted seats)",
  },
] as const;

export type FootprintState = (typeof FOOTPRINT)[number];

export const FOOTPRINT_IDS: Set<string> = new Set(FOOTPRINT.map((s) => s.id));

export const FOOTPRINT_TOTALS = {
  states: FOOTPRINT.length,
  pcs: FOOTPRINT.reduce((a, s) => a + s.pcCount, 0),
  acs: FOOTPRINT.reduce((a, s) => a + s.acCount, 0),
} as const;

/** Named assembly theatres for the footprint ticker — representative, not a dump. */
export const ASSEMBLIES = [
  "Bhopal Madhya",
  "Panipat City",
  "Adarsh Nagar",
  "Katangi",
  "Nabarangpur",
  "Bhawanipatna",
  "Secunderabad",
  "Govindpura",
  "Indore-1",
  "Lashkar",
  "Bhopal Dakshin-Paschim",
  "Karol Bagh",
  "Rajinder Nagar",
  "New Delhi",
  "Chandni Chowk",
  "Model Town",
  "Patel Nagar",
  "Dwarka",
  "R.K. Puram",
  "Greater Kailash",
  "Burari",
  "Borivali",
  "Kandivali East",
  "Shivajinagar",
  "Nagpur South",
  "Thane",
  "Bandra West",
  "Colaba",
  "Chembur",
  "Pune Cantonment",
  "Civil Lines",
  "Kishanpole",
  "Hawa Mahal",
  "Sanganer",
  "Kota North",
  "Jodhpur",
  "Udaipur",
  "Karnal",
  "Panipat Rural",
  "Gurgaon",
  "Faridabad",
  "Rohtak",
  "Hisar",
  "Jalukbari",
  "Dispur",
  "Jorhat",
  "Guwahati East",
  "Silchar",
  "Dibrugarh",
  "Bhubaneswar North",
  "Barabati-Cuttack",
  "Puri",
  "Berhampur",
  "Rourkela",
  "Sambalpur",
  "Khairatabad",
  "Jubilee Hills",
  "Amberpet",
  "Malakpet",
  "Nampally",
  "Serilingampally",
  "Kukatpally",
  "Panaji",
  "Taleigao",
  "Mapusa",
  "Calangute",
  "Ponda",
  "Margao",
  "Vasco",
  "Oupalam",
  "Lawspet",
  "Kamaraj Nagar",
  "Kalapet",
  "Karaikal North",
  "Srinagar",
  "Jammu East",
  "Jammu West",
  "Anantnag",
  "Baramulla",
  "Udhampur",
  "Kathua",
  "Rajouri",
  "Gwalior",
  "Jabalpur West",
  "Balaghat",
  "Ujjain North",
  "Rewa",
  "Satna",
  "Vidisha",
  "Hoshangabad",
] as const;
