/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MandataRouteImport } from './routes/mandata'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ApiInfoRequestRouteImport } from './routes/api.info-request'
import { Route as ApiIntakeRouteImport } from './routes/api.intake'
import { Route as ApiPublicConfigRouteImport } from './routes/api.public-config'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleIntakeRouteImport } from './routes/console.intake'
import { Route as ConsoleWhatsappRouteImport } from './routes/console.whatsapp'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ApiAdminIntakeRouteImport } from './routes/api.admin.intake'
import { Route as ApiAdminWhatsappRouteImport } from './routes/api.admin.whatsapp'
import { Route as ApiSocialWebhookRouteImport } from './routes/api.social.webhook'
import { Route as ApiWhatsappNotifyRouteImport } from './routes/api.whatsapp.notify'
import { Route as ApiWhatsappSendRouteImport } from './routes/api.whatsapp.send'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as ApiXWebhookRouteImport } from './routes/api.x.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MandataRoute = MandataRouteImport.update({
  id: '/mandata',
  path: '/mandata',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfoRequestRoute = ApiInfoRequestRouteImport.update({
  id: '/api/info-request',
  path: '/api/info-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntakeRoute = ApiIntakeRouteImport.update({
  id: '/api/intake',
  path: '/api/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public-config',
  path: '/api/public-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleIntakeRoute = ConsoleIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWhatsappRoute = ConsoleWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => ConsoleRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const ApiAdminIntakeRoute = ApiAdminIntakeRouteImport.update({
  id: '/api/admin/intake',
  path: '/api/admin/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWhatsappRoute = ApiAdminWhatsappRouteImport.update({
  id: '/api/admin/whatsapp',
  path: '/api/admin/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialWebhookRoute = ApiSocialWebhookRouteImport.update({
  id: '/api/social/webhook',
  path: '/api/social/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappNotifyRoute = ApiWhatsappNotifyRouteImport.update({
  id: '/api/whatsapp/notify',
  path: '/api/whatsapp/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappSendRoute = ApiWhatsappSendRouteImport.update({
  id: '/api/whatsapp/send',
  path: '/api/whatsapp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXWebhookRoute = ApiXWebhookRouteImport.update({
  id: '/api/x/webhook',
  path: '/api/x/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/console': typeof ConsoleRouteWithChildren
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/insights': typeof InsightsRouteWithChildren
  '/mandata': typeof MandataRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/work': typeof WorkRoute
  '/api/info-request': typeof ApiInfoRequestRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/public-config': typeof ApiPublicConfigRoute
  '/console/intake': typeof ConsoleIntakeRoute
  '/console/whatsapp': typeof ConsoleWhatsappRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/console/': typeof ConsoleIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/admin/intake': typeof ApiAdminIntakeRoute
  '/api/admin/whatsapp': typeof ApiAdminWhatsappRoute
  '/api/social/webhook': typeof ApiSocialWebhookRoute
  '/api/whatsapp/notify': typeof ApiWhatsappNotifyRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/x/webhook': typeof ApiXWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/mandata': typeof MandataRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/work': typeof WorkRoute
  '/api/info-request': typeof ApiInfoRequestRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/public-config': typeof ApiPublicConfigRoute
  '/console/intake': typeof ConsoleIntakeRoute
  '/console/whatsapp': typeof ConsoleWhatsappRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/console': typeof ConsoleIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/api/admin/intake': typeof ApiAdminIntakeRoute
  '/api/admin/whatsapp': typeof ApiAdminWhatsappRoute
  '/api/social/webhook': typeof ApiSocialWebhookRoute
  '/api/whatsapp/notify': typeof ApiWhatsappNotifyRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/x/webhook': typeof ApiXWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/console': typeof ConsoleRouteWithChildren
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/insights': typeof InsightsRouteWithChildren
  '/mandata': typeof MandataRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/work': typeof WorkRoute
  '/api/info-request': typeof ApiInfoRequestRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/public-config': typeof ApiPublicConfigRoute
  '/console/intake': typeof ConsoleIntakeRoute
  '/console/whatsapp': typeof ConsoleWhatsappRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/console/': typeof ConsoleIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/admin/intake': typeof ApiAdminIntakeRoute
  '/api/admin/whatsapp': typeof ApiAdminWhatsappRoute
  '/api/social/webhook': typeof ApiSocialWebhookRoute
  '/api/whatsapp/notify': typeof ApiWhatsappNotifyRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/x/webhook': typeof ApiXWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/console'
    | '/contact'
    | '/governance'
    | '/insights'
    | '/mandata'
    | '/platform'
    | '/privacy'
    | '/terms'
    | '/track-record'
    | '/work'
    | '/api/info-request'
    | '/api/intake'
    | '/api/public-config'
    | '/console/intake'
    | '/console/whatsapp'
    | '/insights/$slug'
    | '/console/'
    | '/insights/'
    | '/api/admin/intake'
    | '/api/admin/whatsapp'
    | '/api/social/webhook'
    | '/api/whatsapp/notify'
    | '/api/whatsapp/send'
    | '/api/whatsapp/webhook'
    | '/api/x/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/governance'
    | '/mandata'
    | '/platform'
    | '/privacy'
    | '/terms'
    | '/track-record'
    | '/work'
    | '/api/info-request'
    | '/api/intake'
    | '/api/public-config'
    | '/console/intake'
    | '/console/whatsapp'
    | '/insights/$slug'
    | '/console'
    | '/insights'
    | '/api/admin/intake'
    | '/api/admin/whatsapp'
    | '/api/social/webhook'
    | '/api/whatsapp/notify'
    | '/api/whatsapp/send'
    | '/api/whatsapp/webhook'
    | '/api/x/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/console'
    | '/contact'
    | '/governance'
    | '/insights'
    | '/mandata'
    | '/platform'
    | '/privacy'
    | '/terms'
    | '/track-record'
    | '/work'
    | '/api/info-request'
    | '/api/intake'
    | '/api/public-config'
    | '/console/intake'
    | '/console/whatsapp'
    | '/insights/$slug'
    | '/console/'
    | '/insights/'
    | '/api/admin/intake'
    | '/api/admin/whatsapp'
    | '/api/social/webhook'
    | '/api/whatsapp/notify'
    | '/api/whatsapp/send'
    | '/api/whatsapp/webhook'
    | '/api/x/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ContactRoute: typeof ContactRoute
  GovernanceRoute: typeof GovernanceRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  MandataRoute: typeof MandataRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrackRecordRoute: typeof TrackRecordRoute
  WorkRoute: typeof WorkRoute
  ApiInfoRequestRoute: typeof ApiInfoRequestRoute
  ApiIntakeRoute: typeof ApiIntakeRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
  ApiAdminIntakeRoute: typeof ApiAdminIntakeRoute
  ApiAdminWhatsappRoute: typeof ApiAdminWhatsappRoute
  ApiSocialWebhookRoute: typeof ApiSocialWebhookRoute
  ApiWhatsappNotifyRoute: typeof ApiWhatsappNotifyRoute
  ApiWhatsappSendRoute: typeof ApiWhatsappSendRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiXWebhookRoute: typeof ApiXWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandata': {
      id: '/mandata'
      path: '/mandata'
      fullPath: '/mandata'
      preLoaderRoute: typeof MandataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/info-request': {
      id: '/api/info-request'
      path: '/api/info-request'
      fullPath: '/api/info-request'
      preLoaderRoute: typeof ApiInfoRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intake': {
      id: '/api/intake'
      path: '/api/intake'
      fullPath: '/api/intake'
      preLoaderRoute: typeof ApiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-config': {
      id: '/api/public-config'
      path: '/api/public-config'
      fullPath: '/api/public-config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/intake': {
      id: '/console/intake'
      path: '/intake'
      fullPath: '/console/intake'
      preLoaderRoute: typeof ConsoleIntakeRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/whatsapp': {
      id: '/console/whatsapp'
      path: '/whatsapp'
      fullPath: '/console/whatsapp'
      preLoaderRoute: typeof ConsoleWhatsappRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/api/admin/intake': {
      id: '/api/admin/intake'
      path: '/api/admin/intake'
      fullPath: '/api/admin/intake'
      preLoaderRoute: typeof ApiAdminIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/whatsapp': {
      id: '/api/admin/whatsapp'
      path: '/api/admin/whatsapp'
      fullPath: '/api/admin/whatsapp'
      preLoaderRoute: typeof ApiAdminWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/webhook': {
      id: '/api/social/webhook'
      path: '/api/social/webhook'
      fullPath: '/api/social/webhook'
      preLoaderRoute: typeof ApiSocialWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/notify': {
      id: '/api/whatsapp/notify'
      path: '/api/whatsapp/notify'
      fullPath: '/api/whatsapp/notify'
      preLoaderRoute: typeof ApiWhatsappNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/send': {
      id: '/api/whatsapp/send'
      path: '/api/whatsapp/send'
      fullPath: '/api/whatsapp/send'
      preLoaderRoute: typeof ApiWhatsappSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/webhook': {
      id: '/api/x/webhook'
      path: '/api/x/webhook'
      fullPath: '/api/x/webhook'
      preLoaderRoute: typeof ApiXWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleIntakeRoute: typeof ConsoleIntakeRoute
  ConsoleWhatsappRoute: typeof ConsoleWhatsappRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleIntakeRoute: ConsoleIntakeRoute,
  ConsoleWhatsappRoute: ConsoleWhatsappRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  ContactRoute: ContactRoute,
  GovernanceRoute: GovernanceRoute,
  InsightsRoute: InsightsRouteWithChildren,
  MandataRoute: MandataRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrackRecordRoute: TrackRecordRoute,
  WorkRoute: WorkRoute,
  ApiInfoRequestRoute: ApiInfoRequestRoute,
  ApiIntakeRoute: ApiIntakeRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
  ApiAdminIntakeRoute: ApiAdminIntakeRoute,
  ApiAdminWhatsappRoute: ApiAdminWhatsappRoute,
  ApiSocialWebhookRoute: ApiSocialWebhookRoute,
  ApiWhatsappNotifyRoute: ApiWhatsappNotifyRoute,
  ApiWhatsappSendRoute: ApiWhatsappSendRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiXWebhookRoute: ApiXWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
